# -*- coding: utf-8 -*-
"""Math1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZK9MzFclRPKOmL1Rf4yKFY33KCpfMJto
"""

# Loops
I = 0  # declare
while I < 10:  # condition
  print(I)
  I += 1  # increment

A = 1
while A < 10:
  print("Aditi")
  A += 1

# 2*2 = 4
num = 1
while num < 11:
  print(2*num)
  num += 1

n = 2
b = 1
while b < 11:
  value = n * b
  print(n, "*", b , "=" , value )
  b += 1

for a in range(6):
  print(a)

b = ["Aditi","priya","AAchal"]
for d in b:
  print(d)

n = ["Aditi"]
for b in range(7):
  print(n)

for i in range(5,-1,-1):
  print(i)

for n in range(20):
  if n % 2==0:
    print(n)
    break
    continue

print(2/2) # / it use a division symbol get answer in quotient
# % this gives ans in reminder

# without parameter function
def Aditi():
  print("Aditi")


Aditi()

# with parameter
def my_function (name):
  print(2+2)

my_function("Aditi")

def my_function(name,age):
  print(2+2)


my_function("Aditi",21)

def baby_name(*kids):
  print("baby name"+kids[1])


baby_name("a","r","w")

#function call karych ahe output la 2 cha table yayla pahije,function with parameter ,without parameter
#without parameter
def print_table():
  for i in range(1,11):
    print("2 *",i,"=",2*i)


print_table()

#with parameter
def my_table(name):
  for i in range(1,11):
    print("2 *",i,"=",2*i)


my_table("aditi")

s = ("a","b","c","d")
print(s[1])

b = ["P","D","J"]
print(b[2])

b = ["P","D","J"]
b.append("g")
print(b)

s = ("a","b","c","d")
n = list(s)
print(n)
n.append("f")
s = tuple(n)
print(s)

# pack
s = ("a","b","c","d")
for i in s:
  print(i)

# unpack
fruits = ("banana","apple","watermellon")
(yellow,red,green) = fruits
print(red)

t = (1,2,3,4,5,6,7,8,9,10,2,2,2,2)
s = t.count(2)
print(s)

t = (1,2,3,4,5,6,7,8,9,10,2,2,2,2)
s = t.index(8)
print(s)