# -*- coding: utf-8 -*-
"""Math.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZpNCLwtBR8CGsZhWhl631wjfmtH6YBIK
"""

height = int(input())
weight = int(input())
age = int(input())
S = height+weight+age
print(S)

a=10
b=9
if b > a:
  print("a greater than b")
else :
  print("b is greater than a")

a=10
b=10
if b == a:
  print(" both are equal")
else :
  print("not equal")

salary = 10000
if salary >= 50000:
  print("basic salary")
elif salary < 8000:
  print("medium salary")
elif salary == 10000:
  print("top salary")
else:
  print("berojgar")

salary = 10000
if salary != 10000:
  print("basic salary")
elif salary < 8000:
  print("medium salary")
elif salary == 10000:
  print("top salary")
else:
  print("berojgar")

A = 19
B = 10
print(A!=B)

A = 20
B = 22
C = A+B
if C > 40:
  print("C")

# and
a=200
b=33
c=500
if a > b and c > a:
 print("both condition are true")

# or
a=10
b=1
c=1
if a > b or c > a:
 print("both condition are true")

# not
a=33
b=78
if not a > b:
  print("a is not greater than b")

# nested if
x=11
if x > 10:
  print("above 10")
  if x > 20:
    print("x is greater than 20")
  else:
      print("but not above 20")

A=300
B=200
if B > A:
 pass

# short hand if else
a=2700
b=800
print("a") if a > b else print("b")

"""if else"""